---
name: Linux Tests

"on":
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check
        continue-on-error: true

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Build TypeScript
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Run Linux security check tests
        run: |
          chmod +x scripts/testing/test-linux.sh
          scripts/testing/test-linux.sh
        env:
          CI: true
          TESTING_MODE: non-interactive

      - name: Build pkg executable for Linux
        run: npm run pkg:linux

      - name: Test pkg executable - Help command
        run: |
          chmod +x bin/index-linux
          ./bin/index-linux --help

      - name: Test pkg executable - Version command
        run: ./bin/index-linux --version

      - name: Test pkg executable - Check help command
        run: ./bin/index-linux check --help

      - name: Test pkg executable - Basic check (non-interactive)
        run: |
          timeout 30s ./bin/index-linux check relaxed --quiet || true
        env:
          CI: true

      - name: Test global npm install and uninstall
        run: |
          # Test global install
          npm pack
          PACKAGE_FILE=$(ls *.tgz)
          npm install -g "$PACKAGE_FILE"

          # Test globally installed command
          eai-security-check --help
          eai-security-check --version
          eai-security-check check --help

          # Test basic security check (allow failure in CI)
          timeout 30s eai-security-check check relaxed --quiet || true

          # Clean up
          npm uninstall -g eai-security-check
          rm -f *.tgz
        env:
          CI: true

      - name: Test application's global install functionality
        run: |
          # Build and prepare the application
          npm run build

          # Test the application's own global install command
          echo "Testing eai-security-check install command..."
          sudo node dist/cli/index.js install

          # Verify global installation created correct directories
          echo "Verifying installation directories..."
          test -d "/usr/local/lib/eai-security-check" || \
            (echo "❌ Target directory not created" && exit 1)
          test -L "/usr/local/bin/eai-security-check" || \
            (echo "❌ Symlink not created" && exit 1)

          # Test that globally installed command works
          echo "Testing globally installed command..."
          /usr/local/bin/eai-security-check --help
          /usr/local/bin/eai-security-check --version
          /usr/local/bin/eai-security-check check --help

          # Test that the command works from any directory
          cd /tmp
          which eai-security-check
          eai-security-check --version

          # Test basic security check with global install (allow failure)
          echo "Testing basic security check..."
          timeout 30s eai-security-check check relaxed --quiet || echo "Security check completed or timed out (expected in CI)"

          # Test the application's own uninstall command
          echo "Testing eai-security-check uninstall command..."
          sudo eai-security-check uninstall

          # Verify uninstallation cleaned up correctly
          echo "Verifying uninstallation cleanup..."
          test ! -L "/usr/local/bin/eai-security-check" || \
            (echo "❌ Symlink not removed" && exit 1)
          test ! -d "/usr/local/lib/eai-security-check" || \
            (echo "❌ Installation directory not removed" && exit 1)

          echo "✅ Application global install/uninstall functionality works correctly"
        env:
          CI: true

      - name: Upload pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: eai-security-check-linux
          path: bin/index-linux
          retention-days: 7
