name: Quick CI

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [develop, ui-conversion]

permissions:
  contents: read
  checks: write

env:
  NODE_VERSION: '22.x'

jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Run quick verification
        run: |
          chmod +x scripts/test-ci-locally.sh
          ./scripts/test-ci-locally.sh

  build-check:
    name: Build Verification  
    runs-on: ubuntu-latest
    needs: quick-check
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build everything
        run: |
          chmod +x scripts/build-all.sh
          ./scripts/build-all.sh --skip-electron

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            dist/
            bin/
          retention-days: 1
