---
name: Windows Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Run Windows security check tests
        run: |
          powershell.exe -ExecutionPolicy Bypass -File scripts/testing/test-windows.ps1 -Quiet
        env:
          CI: true
          TESTING_MODE: non-interactive

      - name: Build pkg executable for Windows
        run: npm run pkg:windows

      - name: Test pkg executable - Help command
        run: ./bin/index-win.exe --help

      - name: Test pkg executable - Version command
        run: ./bin/index-win.exe --version

      - name: Test pkg executable - Check help command
        run: ./bin/index-win.exe check --help

      - name: Test pkg executable - Basic check (non-interactive)
        run: |
          # Run with timeout and allow failure since security checks may fail in CI
          timeout /t 30 /nobreak > nul & ./bin/index-win.exe check --profile=relaxed --quiet
        env:
          CI: true
        continue-on-error: true

      - name: Upload pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: eai-security-check-windows
          path: bin/index-win.exe
          retention-days: 7